import React, { createContext, useContext, useState, useEffect } from 'react';
import { STORAGE_KEYS } from '../utils/constants';
import { storage } from '../utils/helpers';

export type Language = 'en' | 'sn' | 'nd';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.browse_apps': 'Browse Apps',
    'nav.developers': 'Developers',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    
    // Common
    'common.free': 'Free',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.submit': 'Submit',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.download': 'Download',
    'common.install': 'Install',
    'common.purchase': 'Purchase',
    'common.open': 'Open',
    'common.share': 'Share',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.category': 'Category',
    'common.price': 'Price',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'common.downloads': 'Downloads',
    'common.version': 'Version',
    'common.size': 'Size',
    'common.updated': 'Updated',
    'common.developer': 'Developer',
    'common.description': 'Description',
    'common.screenshots': 'Screenshots',
    'common.requirements': 'Requirements',
    
    // Home page
    'home.hero.title': 'Discover Zimbabwe\'s',
    'home.hero.subtitle': 'Best Mobile Apps',
    'home.hero.description': 'From mobile money to local news, find apps built by Zimbabweans for Zimbabweans. Support local innovation and discover your next favorite app.',
    'home.hero.browse_apps': 'Browse Apps',
    'home.hero.submit_app': 'Submit Your App',
    'home.stats.downloads': 'Total Downloads',
    'home.stats.users': 'Active Users',
    'home.stats.apps': 'Apps Available',
    'home.stats.developers': 'Developers',
    'home.featured.title': 'Featured Apps',
    'home.featured.description': 'Discover the most popular and innovative apps from Zimbabwean developers',
    'home.featured.view_all': 'View All Apps',
    'home.features.title': 'Why Choose ZimbabweApps?',
    'home.features.secure.title': 'Secure & Trusted',
    'home.features.secure.description': 'All apps are verified and secure. We prioritize user safety and data protection.',
    'home.features.payment.title': 'Local Payment',
    'home.features.payment.description': 'Easy payments with EcoCash, PayNow, and other local payment methods.',
    'home.features.support.title': 'Support Local',
    'home.features.support.description': 'Every download supports Zimbabwean developers and innovation.',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.description': 'Join thousands of users discovering amazing apps every day',
    'home.cta.create_account': 'Create Account',
    
    // Apps page
    'apps.title': 'Browse Apps',
    'apps.description': 'Discover amazing apps created by Zimbabwean developers',
    'apps.search_placeholder': 'Search apps...',
    'apps.filters.all_categories': 'All Categories',
    'apps.filters.all_apps': 'All Apps',
    'apps.filters.free_only': 'Free Only',
    'apps.filters.paid_only': 'Paid Only',
    'apps.filters.any_rating': 'Any Rating',
    'apps.filters.stars': '+ Stars',
    'apps.filters.newest': 'Newest First',
    'apps.filters.popular': 'Most Popular',
    'apps.filters.highest_rated': 'Highest Rated',
    'apps.filters.name_az': 'Name (A-Z)',
    'apps.filters.clear_all': 'Clear all',
    'apps.showing_count': 'Showing {count} app',
    'apps.showing_count_plural': 'Showing {count} apps',
    'apps.no_apps_found': 'No apps found.',
    'apps.no_apps_search': 'No apps found matching "{query}"',
    'apps.no_apps_criteria': 'No apps found matching your criteria.',
    
    // App details
    'app.write_review': 'Write Review',
    'app.your_review': 'Your Review',
    'app.about_app': 'About this app',
    'app.app_info': 'App Info',
    'app.visit_website': 'Visit website',
    'app.view_more_apps': 'View more apps →',
    'app.sign_in_download': 'Sign in to download apps',
    'app.verified_purchase': 'Verified Purchase',
    'app.no_reviews': 'No reviews yet. Be the first to review this app!',
    'app.helpful': 'Helpful',
    'app.report': 'Report',
    'app.processing': 'Processing...',
    'app.downloaded_successfully': 'App downloaded successfully!',
    'app.purchased_successfully': 'App purchased and downloaded!',
    'app.access_anytime': 'You can now access this app anytime from your library.',
    'app.download_failed': 'Download failed',
    'app.please_sign_in': 'Please sign in to download apps',
    
    // Reviews
    'review.write_title': 'Write a Review',
    'review.rating_label': 'Rating',
    'review.title_label': 'Title (optional)',
    'review.title_placeholder': 'Summarize your experience',
    'review.comment_label': 'Comment (optional)',
    'review.comment_placeholder': 'Share your thoughts about this app',
    'review.submit': 'Submit Review',
    'review.submitting': 'Submitting...',
    'review.submitted_success': 'Review submitted successfully!',
    'review.delete_confirm': 'Are you sure you want to delete your review?',
    'review.deleted_success': 'Review deleted successfully!',
    'review.submit_failed': 'Failed to submit review',
    'review.delete_failed': 'Failed to delete review',
    
    // Developer
    'developer.portal_title': 'Developer Portal',
    'developer.portal_description_dev': 'Submit and manage your apps on ZimbabweApps',
    'developer.portal_description_user': 'Apply to become a developer and start publishing apps',
    'developer.apply_title': 'Apply to Become a Developer',
    'developer.apply_description': 'Join our community of developers and start publishing your apps on ZimbabweApps.',
    'developer.application_status': 'Developer Application Status',
    'developer.application_submitted': 'Application Submitted',
    'developer.under_review': 'Under Review',
    'developer.approved': 'Approved',
    'developer.rejected': 'Rejected',
    'developer.review_notes': 'Review Notes:',
    'developer.name_label': 'Developer Name *',
    'developer.name_placeholder': 'Your developer name or company name',
    'developer.website_label': 'Website',
    'developer.bio_label': 'Developer Bio *',
    'developer.bio_placeholder': 'Tell us about yourself, your background, and your development experience...',
    'developer.portfolio_label': 'Portfolio Links',
    'developer.portfolio_placeholder': 'https://github.com/yourusername/project',
    'developer.portfolio_help': 'Add links to your GitHub, portfolio website, or published apps',
    'developer.experience_label': 'Years of Experience',
    'developer.experience_select': 'Select experience level',
    'developer.experience_less_1': 'Less than 1 year',
    'developer.experience_1_2': '1-2 years',
    'developer.experience_3_5': '3-5 years',
    'developer.experience_6_10': '6-10 years',
    'developer.experience_10_plus': 'More than 10 years',
    'developer.motivation_label': 'Why do you want to become a developer on ZimbabweApps? *',
    'developer.motivation_placeholder': 'Share your motivation and what you hope to achieve...',
    'developer.what_next': 'What happens next?',
    'developer.review_time': 'We\'ll review your application within 3-5 business days',
    'developer.email_notification': 'You\'ll receive an email notification about the decision',
    'developer.portal_access': 'If approved, you\'ll gain access to the developer portal',
    'developer.submit_apps': 'You can then start submitting apps for review',
    'developer.save_draft': 'Save Draft',
    'developer.submit_application': 'Submit Application',
    'developer.submitting': 'Submitting...',
    'developer.application_success': 'Developer application submitted successfully!',
    'developer.application_review_time': 'We will review your application within 3-5 business days.',
    'developer.application_failed': 'Failed to submit application',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back, {name}!',
    'dashboard.description_dev': 'Manage your apps, analytics, and developer settings',
    'dashboard.description_user': 'Manage your apps, reviews, and account settings',
    'dashboard.published_apps': 'Published Apps',
    'dashboard.total_downloads': 'Total Downloads',
    'dashboard.average_rating': 'Average Rating',
    'dashboard.revenue': 'Revenue',
    'dashboard.apps_downloaded': 'Apps Downloaded',
    'dashboard.reviews_given': 'Reviews Given',
    'dashboard.following': 'Following',
    'dashboard.wishlist': 'Wishlist',
    'dashboard.my_apps': 'My Apps',
    'dashboard.last_used': 'Last used {time}',
    'dashboard.update_available': 'Update Available',
    'dashboard.installed': 'Installed',
    'dashboard.view_all_apps': 'View All Apps →',
    'dashboard.account_info': 'Account Info',
    'dashboard.email': 'Email',
    'dashboard.name': 'Name',
    'dashboard.account_type': 'Account Type',
    'dashboard.developer_name': 'Developer Name',
    'dashboard.member_since': 'Member Since',
    'dashboard.edit_profile': 'Edit Profile',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.browse_new_apps': 'Browse New Apps',
    'dashboard.update_apps': 'Update Apps',
    'dashboard.view_reviews': 'View Reviews',
    'dashboard.submit_new_app': 'Submit New App',
    'dashboard.access_denied': 'Access Denied',
    'dashboard.please_login': 'Please log in to access your dashboard.',
    'dashboard.sign_in': 'Sign In',
    
    // Auth
    'auth.sign_in_title': 'Sign in to your account',
    'auth.create_account_link': 'create a new account',
    'auth.sign_in_existing_link': 'sign in to your existing account',
    'auth.create_account_title': 'Create your account',
    'auth.email_label': 'Email address',
    'auth.email_placeholder': 'Enter your email',
    'auth.password_label': 'Password',
    'auth.password_placeholder': 'Enter your password',
    'auth.confirm_password_label': 'Confirm password',
    'auth.confirm_password_placeholder': 'Confirm your password',
    'auth.full_name_label': 'Full name',
    'auth.full_name_placeholder': 'Enter your full name',
    'auth.account_type_label': 'Account type',
    'auth.account_type_user': 'App User',
    'auth.account_type_developer': 'App Developer',
    'auth.account_type_user_desc': 'Choose this to browse and download apps',
    'auth.account_type_developer_desc': 'Choose this if you want to submit apps to the store',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot your password?',
    'auth.sign_in_button': 'Sign in',
    'auth.signing_in': 'Signing in...',
    'auth.create_account_button': 'Create account',
    'auth.creating_account': 'Creating account...',
    'auth.demo_account': 'Demo Account',
    'auth.use_demo': 'Use Demo Account',
    'auth.agree_terms': 'I agree to the',
    'auth.terms_service': 'Terms of Service',
    'auth.privacy_policy': 'Privacy Policy',
    'auth.invalid_credentials': 'Invalid email or password',
    'auth.account_creation_failed': 'Failed to create account',
    'auth.passwords_no_match': 'Passwords do not match',
    'auth.password_min_length': 'Password must be at least 6 characters',
    
    // Footer
    'footer.description': 'Zimbabwe\'s premier book marketplace. Discover, download, and support local authors creating innovative solutions for our digital future.',
    'footer.location': 'Harare, Zimbabwe',
    'footer.quick_links': 'Quick Links',
    'footer.about_us': 'About Us',
    'footer.contact': 'Contact',
    'footer.support': 'Support',
    'footer.help_center': 'Help Center',
    'footer.terms_service': 'Terms of Service',
    'footer.payment_info': 'Payment Info',
    'footer.copyright': '© 2025 Book-Case. All rights reserved.',
    'footer.support_email': 'support@book-case.co.zw',
    
    // Search
    'search.recent_searches': 'Recent Searches',
    'search.trending': 'Trending',
    'search.clear': 'Clear',
    
    // Categories
    'category.finance': 'Finance',
    'category.news': 'News',
    'category.weather': 'Weather',
    'category.travel': 'Travel',
    'category.education': 'Education',
    'category.entertainment': 'Entertainment',
    'category.business': 'Business',
    'category.health': 'Health',
    'category.shopping': 'Shopping',
    'category.social': 'Social',
    'category.productivity': 'Productivity',
    'category.games': 'Games',
  },
  
  sn: {
    // Navigation
    'nav.browse_apps': 'Tsvaga Mapurogiramu',
    'nav.developers': 'Vagadziri',
    'nav.login': 'Pinda',
    'nav.signup': 'Nyoresa',
    'nav.dashboard': 'Dashidhobhodi',
    'nav.logout': 'Buda',
    
    // Common
    'common.free': 'Mahara',
    'common.loading': 'Kutakura...',
    'common.error': 'Kukanganisa',
    'common.success': 'Kubudirira',
    'common.cancel': 'Kanzura',
    'common.save': 'Chengetedza',
    'common.submit': 'Tumira',
    'common.edit': 'Gadzirisa',
    'common.delete': 'Bvisa',
    'common.view': 'Ona',
    'common.download': 'Dhawunirodha',
    'common.install': 'Isa',
    'common.purchase': 'Tenga',
    'common.open': 'Vhura',
    'common.share': 'Govera',
    'common.search': 'Tsvaga',
    'common.filter': 'Sefa',
    'common.sort': 'Ronga',
    'common.category': 'Chikamu',
    'common.price': 'Mutengo',
    'common.rating': 'Chiyero',
    'common.reviews': 'Ongororo',
    'common.downloads': 'Dhawunirodha',
    'common.version': 'Shanduko',
    'common.size': 'Saizi',
    'common.updated': 'Gadziriswa',
    'common.developer': 'Mugadziri',
    'common.description': 'Tsanangudzo',
    'common.screenshots': 'Mifananidzo',
    'common.requirements': 'Zvinodiwa',
    
    // Home page
    'home.hero.title': 'Wana Mapurogiramu',
    'home.hero.subtitle': 'Akanakisa eZimbabwe',
    'home.hero.description': 'Kubva kumari yemahara kusvika kunhau dzemuno, wana mapurogiramu akagadzirwa nevaZimbabwe kune vaZimbabwe. Tsigira hunyanzvi hwemuno uye wana purogiramu yako inotevera.',
    'home.hero.browse_apps': 'Tsvaga Mapurogiramu',
    'home.hero.submit_app': 'Tumira Purogiramu Yako',
    'home.stats.downloads': 'Dhawunirodha Dzose',
    'home.stats.users': 'Vashandisi Vanoshanda',
    'home.stats.apps': 'Mapurogiramu Aripo',
    'home.stats.developers': 'Vagadziri',
    'home.featured.title': 'Mapurogiramu Akakurumbira',
    'home.featured.description': 'Wana mapurogiramu akakurumbira uye ane hunyanzvi kubva kuvagadziri veZimbabwe',
    'home.featured.view_all': 'Ona Mapurogiramu Ose',
    'home.features.title': 'Nei Uchisarudza ZimbabweApps?',
    'home.features.secure.title': 'Yakachengeteka & Yakavimbika',
    'home.features.secure.description': 'Mapurogiramu ose akaongororwa uye akachengeteka. Tinoisa pamberi kuchengeteka kwevashandisi uye kudzivirira kwedata.',
    'home.features.payment.title': 'Kubhadhara Kwemuno',
    'home.features.payment.description': 'Kubhadhara kuri nyore neEcoCash, PayNow, uye dzimwe nzira dzekubhadhara dzemuno.',
    'home.features.support.title': 'Tsigira Zvemuno',
    'home.features.support.description': 'Dhawunirodha yega yega inotsigira vagadziri veZimbabwe uye hunyanzvi.',
    'home.cta.title': 'Wakagadzirira Kutanga?',
    'home.cta.description': 'Joina zviuru zvevashandisi vanowana mapurogiramu anoshamisa mazuva ose',
    'home.cta.create_account': 'Gadzira Akaundi',
    
    // Apps page
    'apps.title': 'Tsvaga Mapurogiramu',
    'apps.description': 'Wana mapurogiramu anoshamisa akagadzirwa nevagadziri veZimbabwe',
    'apps.search_placeholder': 'Tsvaga mapurogiramu...',
    'apps.filters.all_categories': 'Zvikamu Zvose',
    'apps.filters.all_apps': 'Mapurogiramu Ose',
    'apps.filters.free_only': 'Mahara Chete',
    'apps.filters.paid_only': 'Anobhadharwa Chete',
    'apps.filters.any_rating': 'Chiyero Chipi Zvacho',
    'apps.filters.stars': '+ Nyeredzi',
    'apps.filters.newest': 'Zvitsva Zvekutanga',
    'apps.filters.popular': 'Zvakakurumbira',
    'apps.filters.highest_rated': 'Zvine Chiyero Chepamusoro',
    'apps.filters.name_az': 'Zita (A-Z)',
    'apps.filters.clear_all': 'Bvisa zvose',
    'apps.showing_count': 'Kuratidza purogiramu {count}',
    'apps.showing_count_plural': 'Kuratidza mapurogiramu {count}',
    'apps.no_apps_found': 'Hapana mapurogiramu akawanikwa.',
    'apps.no_apps_search': 'Hapana mapurogiramu akawanikwa anoenderana ne"{query}"',
    'apps.no_apps_criteria': 'Hapana mapurogiramu akawanikwa anoenderana nezvawakatsvaga.',
    
    // App details
    'app.write_review': 'Nyora Ongororo',
    'app.your_review': 'Ongororo Yako',
    'app.about_app': 'Nezve purogiramu ino',
    'app.app_info': 'Ruzivo rwePurogiramu',
    'app.visit_website': 'Shanyira webhusaiti',
    'app.view_more_apps': 'Ona mamwe mapurogiramu →',
    'app.sign_in_download': 'Pinda kuti udhawunirodhe mapurogiramu',
    'app.verified_purchase': 'Kutenga Kwakasimbiswa',
    'app.no_reviews': 'Hapana ongororo parizvino. Iva wekutanga kuongorora purogiramu ino!',
    'app.helpful': 'Inobatsira',
    'app.report': 'Shuma',
    'app.processing': 'Kugadzirisa...',
    'app.downloaded_successfully': 'Purogiramu yadhawunirodha zvakanaka!',
    'app.purchased_successfully': 'Purogiramu yatengwa uye yadhawunirodha!',
    'app.access_anytime': 'Unogona kuwana purogiramu ino chero nguva kubva mulibrari yako.',
    'app.download_failed': 'Dhawunirodha yakundikana',
    'app.please_sign_in': 'Ndapota pinda kuti udhawunirodhe mapurogiramu',
    
    // Reviews
    'review.write_title': 'Nyora Ongororo',
    'review.rating_label': 'Chiyero',
    'review.title_label': 'Musoro (usina kumanikidzwa)',
    'review.title_placeholder': 'Pfupisa ruzivo rwako',
    'review.comment_label': 'Komendi (usina kumanikidzwa)',
    'review.comment_placeholder': 'Govera pfungwa dzako nezve purogiramu ino',
    'review.submit': 'Tumira Ongororo',
    'review.submitting': 'Kutumira...',
    'review.submitted_success': 'Ongororo yatumirwa zvakanaka!',
    'review.delete_confirm': 'Uri chokwadi here kuti unoda kubvisa ongororo yako?',
    'review.deleted_success': 'Ongororo yabviswa zvakanaka!',
    'review.submit_failed': 'Kutumira ongororo kwakundikana',
    'review.delete_failed': 'Kubvisa ongororo kwakundikana',
    
    // Developer
    'developer.portal_title': 'Chikoro cheVagadziri',
    'developer.portal_description_dev': 'Tumira uye utungamire mapurogiramu ako paZimbabweApps',
    'developer.portal_description_user': 'Nyorera kuve mugadziri uye utange kuburitsa mapurogiramu',
    'developer.apply_title': 'Nyorera Kuve Mugadziri',
    'developer.apply_description': 'Joina nharaunda yedu yevagadziri uye utange kuburitsa mapurogiramu ako paZimbabweApps.',
    'developer.application_status': 'Mamiriro eChikumbiro cheMugadziri',
    'developer.application_submitted': 'Chikumbiro Chatumirwa',
    'developer.under_review': 'Chiri Kuongororwa',
    'developer.approved': 'Chabvumidzwa',
    'developer.rejected': 'Charambidzwa',
    'developer.review_notes': 'Zvinyorwa zveOngororo:',
    'developer.name_label': 'Zita reMugadziri *',
    'developer.name_placeholder': 'Zita rako remugadziri kana rekambani',
    'developer.website_label': 'Webhusaiti',
    'developer.bio_label': 'Bio yeMugadziri *',
    'developer.bio_placeholder': 'Tiudze nezve iwe, mamiriro ako, uye ruzivo rwako rwekugadzira...',
    'developer.portfolio_label': 'Mabatanidzwa ePortfolio',
    'developer.portfolio_placeholder': 'https://github.com/yourusername/project',
    'developer.portfolio_help': 'Wedzera mabatanidzwa kuGitHub, portfolio webhusaiti, kana mapurogiramu akaburitswa',
    'developer.experience_label': 'Makore eRuzivo',
    'developer.experience_select': 'Sarudza chikamu cheruzivo',
    'developer.experience_less_1': 'Pasi pegore rimwe',
    'developer.experience_1_2': 'Gore 1-2',
    'developer.experience_3_5': 'Makore 3-5',
    'developer.experience_6_10': 'Makore 6-10',
    'developer.experience_10_plus': 'Anopfuura makore 10',
    'developer.motivation_label': 'Nei uchida kuve mugadziri paZimbabweApps? *',
    'developer.motivation_placeholder': 'Govera chikurudziro chako uye zvaunoda kuita...',
    'developer.what_next': 'Chii chinotevera?',
    'developer.review_time': 'Tichaongorora chikumbiro chako mukati memazuva 3-5 ebasa',
    'developer.email_notification': 'Uchawana email yekuzivisa nezve sarudzo',
    'developer.portal_access': 'Kana chabvumidzwa, uchawana mukana wekupinda muchikoro chevagadziri',
    'developer.submit_apps': 'Ipapo unogona kutanga kutumira mapurogiramu kuti aongororwe',
    'developer.save_draft': 'Chengetedza Draft',
    'developer.submit_application': 'Tumira Chikumbiro',
    'developer.submitting': 'Kutumira...',
    'developer.application_success': 'Chikumbiro chemugadziri chatumirwa zvakanaka!',
    'developer.application_review_time': 'Tichaongorora chikumbiro chako mukati memazuva 3-5 ebasa.',
    'developer.application_failed': 'Kutumira chikumbiro kwakundikana',
    
    // Dashboard
    'dashboard.welcome': 'Wakadzokerazve, {name}!',
    'dashboard.description_dev': 'Tungamira mapurogiramu ako, ongororo, uye zvigadziriso zvevagadziri',
    'dashboard.description_user': 'Tungamira mapurogiramu ako, ongororo, uye zvigadziriso zveakaundi',
    'dashboard.published_apps': 'Mapurogiramu Akaburitswa',
    'dashboard.total_downloads': 'Dhawunirodha Dzose',
    'dashboard.average_rating': 'Chiyero Chepakati',
    'dashboard.revenue': 'Mari Yakawanikwa',
    'dashboard.apps_downloaded': 'Mapurogiramu Akadhawunirodha',
    'dashboard.reviews_given': 'Ongororo Dzakapiwa',
    'dashboard.following': 'Kutevera',
    'dashboard.wishlist': 'Runyorwa rwezvishuwo',
    'dashboard.my_apps': 'Mapurogiramu Angu',
    'dashboard.last_used': 'Yakashandiswa pakupedzisira {time}',
    'dashboard.update_available': 'Update Iripo',
    'dashboard.installed': 'Yakaiswa',
    'dashboard.view_all_apps': 'Ona Mapurogiramu Ose →',
    'dashboard.account_info': 'Ruzivo rweAkaundi',
    'dashboard.email': 'Email',
    'dashboard.name': 'Zita',
    'dashboard.account_type': 'Rudzi rweAkaundi',
    'dashboard.developer_name': 'Zita reMugadziri',
    'dashboard.member_since': 'Nhengo Kubva',
    'dashboard.edit_profile': 'Gadzirisa Profile',
    'dashboard.quick_actions': 'Zviito Zvekukurumidza',
    'dashboard.browse_new_apps': 'Tsvaga Mapurogiramu Matsva',
    'dashboard.update_apps': 'Gadzirisa Mapurogiramu',
    'dashboard.view_reviews': 'Ona Ongororo',
    'dashboard.submit_new_app': 'Tumira Purogiramu Itsva',
    'dashboard.access_denied': 'Kupinda Kwarambidzwa',
    'dashboard.please_login': 'Ndapota pinda kuti uwane dashidhobhodi yako.',
    'dashboard.sign_in': 'Pinda',
    
    // Auth
    'auth.sign_in_title': 'Pinda muakaundi yako',
    'auth.create_account_link': 'gadzira akaundi itsva',
    'auth.sign_in_existing_link': 'pinda muakaundi yako iripo',
    'auth.create_account_title': 'Gadzira akaundi yako',
    'auth.email_label': 'Email address',
    'auth.email_placeholder': 'Isa email yako',
    'auth.password_label': 'Password',
    'auth.password_placeholder': 'Isa password yako',
    'auth.confirm_password_label': 'Simbisa password',
    'auth.confirm_password_placeholder': 'Simbisa password yako',
    'auth.full_name_label': 'Zita rakazara',
    'auth.full_name_placeholder': 'Isa zita rako rakazara',
    'auth.account_type_label': 'Rudzi rweakaundi',
    'auth.account_type_user': 'Mushandisi wePurogiramu',
    'auth.account_type_developer': 'Mugadziri wePurogiramu',
    'auth.account_type_user_desc': 'Sarudza ichi kuti utsvage uye udhawunirodhe mapurogiramu',
    'auth.account_type_developer_desc': 'Sarudza ichi kana uchida kutumira mapurogiramu kuchitoro',
    'auth.remember_me': 'Ndirangarire',
    'auth.forgot_password': 'Wakanganwa password yako?',
    'auth.sign_in_button': 'Pinda',
    'auth.signing_in': 'Kupinda...',
    'auth.create_account_button': 'Gadzira akaundi',
    'auth.creating_account': 'Kugadzira akaundi...',
    'auth.demo_account': 'Demo Akaundi',
    'auth.use_demo': 'Shandisa Demo Akaundi',
    'auth.agree_terms': 'Ndinobvuma',
    'auth.terms_service': 'Mitemo yeService',
    'auth.privacy_policy': 'Privacy Policy',
    'auth.invalid_credentials': 'Email kana password isina kukodzera',
    'auth.account_creation_failed': 'Kugadzira akaundi kwakundikana',
    'auth.passwords_no_match': 'Passwords hadzifanane',
    'auth.password_min_length': 'Password inofanira kuve nemavara anosvika 6',
    
    // Footer
    'footer.description': 'Musika mukuru wemapurogiramu emahara weZimbabwe. Wana, dhawunirodha, uye tsigira vagadziri vemuno vanogadzira mhinduro dzine hunyanzvi dzere ramangwana redu.',
    'footer.location': 'Harare, Zimbabwe',
    'footer.quick_links': 'Mabatanidzwa Ekukurumidza',
    'footer.about_us': 'Nezve Isu',
    'footer.contact': 'Batana Nesu',
    'footer.support': 'Rutsigiro',
    'footer.help_center': 'Nzvimbo yeRubatsiro',
    'footer.terms_service': 'Mitemo yeService',
    'footer.payment_info': 'Ruzivo rweKubhadhara',
    'footer.copyright': '© 2025 ZimbabweApps. Kodzero dzose dzakachengetedzwa.',
    'footer.support_email': 'support@zimbabweapps.co.zw',
    
    // Search
    'search.recent_searches': 'Kutsvaga Kwachangopfuura',
    'search.trending': 'Zviri Kutenderera',
    'search.clear': 'Bvisa',
    
    // Categories
    'category.finance': 'Mari',
    'category.news': 'Nhau',
    'category.weather': 'Mamiriro eKunze',
    'category.travel': 'Kufamba',
    'category.education': 'Dzidzo',
    'category.entertainment': 'Varaidzo',
    'category.business': 'Bhizinesi',
    'category.health': 'Hutano',
    'category.shopping': 'Kutenga',
    'category.social': 'Magariro',
    'category.productivity': 'Kubudirira',
    'category.games': 'Mitambo',
  },
  
  nd: {
    // Navigation
    'nav.browse_apps': 'Dinga Izinhlelo',
    'nav.developers': 'Abakhi',
    'nav.login': 'Ngena',
    'nav.signup': 'Zibhalise',
    'nav.dashboard': 'I-Dashboard',
    'nav.logout': 'Phuma',
    
    // Common
    'common.free': 'Mahhala',
    'common.loading': 'Kulayisha...',
    'common.error': 'Iphutha',
    'common.success': 'Impumelelo',
    'common.cancel': 'Khansela',
    'common.save': 'Gcina',
    'common.submit': 'Thumela',
    'common.edit': 'Hlela',
    'common.delete': 'Susa',
    'common.view': 'Bona',
    'common.download': 'Dawuniloda',
    'common.install': 'Faka',
    'common.purchase': 'Thenga',
    'common.open': 'Vula',
    'common.share': 'Yabelana',
    'common.search': 'Dinga',
    'common.filter': 'Hlungisa',
    'common.sort': 'Hlela',
    'common.category': 'Isigaba',
    'common.price': 'Intengo',
    'common.rating': 'Isilinganiso',
    'common.reviews': 'Ukubuyekezwa',
    'common.downloads': 'Ukudawuniloda',
    'common.version': 'Inguqulo',
    'common.size': 'Ubukhulu',
    'common.updated': 'Kubuyekezwe',
    'common.developer': 'Umakhi',
    'common.description': 'Incazelo',
    'common.screenshots': 'Izithombe',
    'common.requirements': 'Izidingo',
    
    // Home page
    'home.hero.title': 'Thola Izinhlelo',
    'home.hero.subtitle': 'Ezinhle kakhulu ZaseZimbabwe',
    'home.hero.description': 'Kusukela emali yeselula kuya ezindabeni zendawo, thola izinhlelo ezakhiwe ngamaZimbabwe kumaZimbabwe. Sekela ukusungula kwendawo futhi uthole uhlelo lwakho olulandelayo.',
    'home.hero.browse_apps': 'Dinga Izinhlelo',
    'home.hero.submit_app': 'Thumela Uhlelo Lwakho',
    'home.stats.downloads': 'Ukudawuniloda Konke',
    'home.stats.users': 'Abasebenzisi Abaphilayo',
    'home.stats.apps': 'Izinhlelo Ezikhona',
    'home.stats.developers': 'Abakhi',
    'home.featured.title': 'Izinhlelo Ezivelele',
    'home.featured.description': 'Thola izinhlelo ezidumile futhi ezintsha ezivela kubakhi baseZimbabwe',
    'home.featured.view_all': 'Bona Zonke Izinhlelo',
    'home.features.title': 'Kungani Ukhetha ZimbabweApps?',
    'home.features.secure.title': 'Kuphephile & Kuthembekile',
    'home.features.secure.description': 'Zonke izinhlelo ziqinisekisiwe futhi ziphephile. Sibeka phambili ukuphepha kwabasebenzisi nokuvikela idatha.',
    'home.features.payment.title': 'Ukukhokha Kwendawo',
    'home.features.payment.description': 'Ukukhokha okulula nge-EcoCash, PayNow, nezinye izindlela zokukhokha zendawo.',
    'home.features.support.title': 'Sekela Okwendawo',
    'home.features.support.description': 'Ukudawuniloda ngakunye kusekela abakhi baseZimbabwe nokusungula.',
    'home.cta.title': 'Usukulungele Ukuqala?',
    'home.cta.description': 'Joyina izinkulungwane zabasebenzisi abathola izinhlelo ezimangalisayo nsuku zonke',
    'home.cta.create_account': 'Dala I-akhawunti',
    
    // Apps page
    'apps.title': 'Dinga Izinhlelo',
    'apps.description': 'Thola izinhlelo ezimangalisayo ezakhiwe ngabakhi baseZimbabwe',
    'apps.search_placeholder': 'Dinga izinhlelo...',
    'apps.filters.all_categories': 'Zonke Izigaba',
    'apps.filters.all_apps': 'Zonke Izinhlelo',
    'apps.filters.free_only': 'Mahhala Kuphela',
    'apps.filters.paid_only': 'Okukhokhelwayo Kuphela',
    'apps.filters.any_rating': 'Noma Yisiphi Isilinganiso',
    'apps.filters.stars': '+ Izinkanyezi',
    'apps.filters.newest': 'Okutsha Kuqala',
    'apps.filters.popular': 'Okudumile Kakhulu',
    'apps.filters.highest_rated': 'Okulinganiswe Phezulu',
    'apps.filters.name_az': 'Igama (A-Z)',
    'apps.filters.clear_all': 'Susa konke',
    'apps.showing_count': 'Kubonisa uhlelo {count}',
    'apps.showing_count_plural': 'Kubonisa izinhlelo {count}',
    'apps.no_apps_found': 'Azikho izinhlelo ezitholiwe.',
    'apps.no_apps_search': 'Azikho izinhlelo ezitholiwe ezifana no-"{query}"',
    'apps.no_apps_criteria': 'Azikho izinhlelo ezitholiwe ezifana nezinto ozidingayo.',
    
    // App details
    'app.write_review': 'Bhala Ukubuyekezwa',
    'app.your_review': 'Ukubuyekezwa Kwakho',
    'app.about_app': 'Mayelana nale nhlelo',
    'app.app_info': 'Ulwazi Lohlelo',
    'app.visit_website': 'Vakashela iwebhusayithi',
    'app.view_more_apps': 'Bona ezinye izinhlelo →',
    'app.sign_in_download': 'Ngena ukuze udawunilode izinhlelo',
    'app.verified_purchase': 'Ukuthenga Okuqinisekisiwe',
    'app.no_reviews': 'Azikho ukubuyekezwa okwamanje. Yiba owokuqala ukubuyekeza le nhlelo!',
    'app.helpful': 'Kuyasiza',
    'app.report': 'Bika',
    'app.processing': 'Kucutshungulwa...',
    'app.downloaded_successfully': 'Uhlelo ludawunilodwe ngempumelelo!',
    'app.purchased_successfully': 'Uhlelo luthengwe futhi lwadawunilodwa!',
    'app.access_anytime': 'Ungafinyelela kule nhlelo nganoma yisiphi isikhathi emtatsheni wakho.',
    'app.download_failed': 'Ukudawuniloda kuhlulekile',
    'app.please_sign_in': 'Sicela ungene ukuze udawunilode izinhlelo',
    
    // Reviews
    'review.write_title': 'Bhala Ukubuyekezwa',
    'review.rating_label': 'Isilinganiso',
    'review.title_label': 'Isihloko (akuphoqelekile)',
    'review.title_placeholder': 'Fingqa isipiliyoni sakho',
    'review.comment_label': 'Amazwana (akuphoqelekile)',
    'review.comment_placeholder': 'Yabelana ngemicabango yakho ngale nhlelo',
    'review.submit': 'Thumela Ukubuyekezwa',
    'review.submitting': 'Kuthumelwa...',
    'review.submitted_success': 'Ukubuyekezwa kuthunyelelwe ngempumelelo!',
    'review.delete_confirm': 'Uqinisekile ukuthi ufuna ukususa ukubuyekezwa kwakho?',
    'review.deleted_success': 'Ukubuyekezwa kususiwe ngempumelelo!',
    'review.submit_failed': 'Ukuthumela ukubuyekezwa kuhlulekile',
    'review.delete_failed': 'Ukususa ukubuyekezwa kuhlulekile',
    
    // Developer
    'developer.portal_title': 'Isango Labakhi',
    'developer.portal_description_dev': 'Thumela futhi uphathe izinhlelo zakho ku-ZimbabweApps',
    'developer.portal_description_user': 'Faka isicelo sokuba umakhi futhi uqale ukukhipha izinhlelo',
    'developer.apply_title': 'Faka Isicelo Sokuba Umakhi',
    'developer.apply_description': 'Joyina umphakathi wethu wabakhi futhi uqale ukukhipha izinhlelo zakho ku-ZimbabweApps.',
    'developer.application_status': 'Isimo Sesicelo Somakhi',
    'developer.application_submitted': 'Isicelo Sithunyelelwe',
    'developer.under_review': 'Siyabuyekezwa',
    'developer.approved': 'Samukelwe',
    'developer.rejected': 'Senqatshelwe',
    'developer.review_notes': 'Amanothi Okubuyekezwa:',
    'developer.name_label': 'Igama Lomakhi *',
    'developer.name_placeholder': 'Igama lakho lomakhi noma lenkampani',
    'developer.website_label': 'Iwebhusayithi',
    'developer.bio_label': 'I-Bio Yomakhi *',
    'developer.bio_placeholder': 'Sitshele ngawe, isizinda sakho, nolwazi lwakho lokwakha...',
    'developer.portfolio_label': 'Izixhumanisi Ze-Portfolio',
    'developer.portfolio_placeholder': 'https://github.com/yourusername/project',
    'developer.portfolio_help': 'Engeza izixhumanisi ku-GitHub, iwebhusayithi ye-portfolio, noma izinhlelo ezikhishiwe',
    'developer.experience_label': 'Iminyaka Yolwazi',
    'developer.experience_select': 'Khetha izinga lolwazi',
    'developer.experience_less_1': 'Ngaphansi konyaka owodwa',
    'developer.experience_1_2': 'Unyaka 1-2',
    'developer.experience_3_5': 'Iminyaka 3-5',
    'developer.experience_6_10': 'Iminyaka 6-10',
    'developer.experience_10_plus': 'Ngaphezu kweminyaka 10',
    'developer.motivation_label': 'Kungani ufuna ukuba umakhi ku-ZimbabweApps? *',
    'developer.motivation_placeholder': 'Yabelana ngokukhuthaza kwakho nokho okufuna ukukufeza...',
    'developer.what_next': 'Yini elandelayo?',
    'developer.review_time': 'Sizobuyekeza isicelo sakho phakathi kwezinsuku 3-5 zomsebenzi',
    'developer.email_notification': 'Uzothola isaziso se-imeyili mayelana nesinqumo',
    'developer.portal_access': 'Uma samukelwe, uzothola ukufinyelela esangweni labakhi',
    'developer.submit_apps': 'Khona-ke ungaqala ukuthumela izinhlelo ukuze zibuyekezwe',
    'developer.save_draft': 'Gcina I-Draft',
    'developer.submit_application': 'Thumela Isicelo',
    'developer.submitting': 'Kuthumelwa...',
    'developer.application_success': 'Isicelo somakhi sithunyelelwe ngempumelelo!',
    'developer.application_review_time': 'Sizobuyekeza isicelo sakho phakathi kwezinsuku 3-5 zomsebenzi.',
    'developer.application_failed': 'Ukuthumela isicelo kuhlulekile',
    
    // Dashboard
    'dashboard.welcome': 'Sawubona futhi, {name}!',
    'dashboard.description_dev': 'Phathe izinhlelo zakho, ukuhlaziya, nezilungiselelo zabakhi',
    'dashboard.description_user': 'Phathe izinhlelo zakho, ukubuyekezwa, nezilungiselelo ze-akhawunti',
    'dashboard.published_apps': 'Izinhlelo Ezikhishiwe',
    'dashboard.total_downloads': 'Ukudawuniloda Konke',
    'dashboard.average_rating': 'Isilinganiso Esimaphakathi',
    'dashboard.revenue': 'Imali Engenayo',
    'dashboard.apps_downloaded': 'Izinhlelo Ezidawunilodwe',
    'dashboard.reviews_given': 'Ukubuyekezwa Okunikeziwe',
    'dashboard.following': 'Ukulandela',
    'dashboard.wishlist': 'Uhlu Lwezifiso',
    'dashboard.my_apps': 'Izinhlelo Zami',
    'dashboard.last_used': 'Yasetshenziswa kamuva {time}',
    'dashboard.update_available': 'Isibuyekezo Siyatholakala',
    'dashboard.installed': 'Kufakiwe',
    'dashboard.view_all_apps': 'Bona Zonke Izinhlelo →',
    'dashboard.account_info': 'Ulwazi Lwe-akhawunti',
    'dashboard.email': 'I-imeyili',
    'dashboard.name': 'Igama',
    'dashboard.account_type': 'Uhlobo Lwe-akhawunti',
    'dashboard.developer_name': 'Igama Lomakhi',
    'dashboard.member_since': 'Ilungu Kusukela',
    'dashboard.edit_profile': 'Hlela Iphrofayili',
    'dashboard.quick_actions': 'Izenzo Ezisheshayo',
    'dashboard.browse_new_apps': 'Dinga Izinhlelo Ezintsha',
    'dashboard.update_apps': 'Buyekeza Izinhlelo',
    'dashboard.view_reviews': 'Bona Ukubuyekezwa',
    'dashboard.submit_new_app': 'Thumela Uhlelo Olusha',
    'dashboard.access_denied': 'Ukufinyelela Kwenqatshelwe',
    'dashboard.please_login': 'Sicela ungene ukuze ufinyelele ku-dashboard yakho.',
    'dashboard.sign_in': 'Ngena',
    
    // Auth
    'auth.sign_in_title': 'Ngena ku-akhawunti yakho',
    'auth.create_account_link': 'dala i-akhawunti entsha',
    'auth.sign_in_existing_link': 'ngena ku-akhawunti yakho ekhona',
    'auth.create_account_title': 'Dala i-akhawunti yakho',
    'auth.email_label': 'Ikheli le-imeyili',
    'auth.email_placeholder': 'Faka i-imeyili yakho',
    'auth.password_label': 'Iphasiwedi',
    'auth.password_placeholder': 'Faka iphasiwedi yakho',
    'auth.confirm_password_label': 'Qinisekisa iphasiwedi',
    'auth.confirm_password_placeholder': 'Qinisekisa iphasiwedi yakho',
    'auth.full_name_label': 'Igama eliphelele',
    'auth.full_name_placeholder': 'Faka igama lakho eliphelele',
    'auth.account_type_label': 'Uhlobo lwe-akhawunti',
    'auth.account_type_user': 'Umsebenzisi Wohlelo',
    'auth.account_type_developer': 'Umakhi Wohlelo',
    'auth.account_type_user_desc': 'Khetha lokhu ukuze udinge futhi udawunilode izinhlelo',
    'auth.account_type_developer_desc': 'Khetha lokhu uma ufuna ukuthumela izinhlelo esitolo',
    'auth.remember_me': 'Ngikhumbule',
    'auth.forgot_password': 'Ukhohlwe iphasiwedi yakho?',
    'auth.sign_in_button': 'Ngena',
    'auth.signing_in': 'Kungenwa...',
    'auth.create_account_button': 'Dala i-akhawunti',
    'auth.creating_account': 'Kudaliwa i-akhawunti...',
    'auth.demo_account': 'I-akhawunti Yesibonelo',
    'auth.use_demo': 'Sebenzisa I-akhawunti Yesibonelo',
    'auth.agree_terms': 'Ngiyavuma',
    'auth.terms_service': 'Imigomo Yesevisi',
    'auth.privacy_policy': 'Inqubomgomo Yobumfihlo',
    'auth.invalid_credentials': 'I-imeyili noma iphasiwedi engalungile',
    'auth.account_creation_failed': 'Ukudala i-akhawunti kuhlulekile',
    'auth.passwords_no_match': 'Amaphasiwedi awafani',
    'auth.password_min_length': 'Iphasiwedi kufanele ibe nezinhlamvu okungenani ezingu-6',
    
    // Footer
    'footer.description': 'Imakethe enkulu yezinhlelo zeselula yaseZimbabwe. Thola, dawuniloda, futhi usekele abakhi bendawo abadala izixazululo ezintsha zeikusasa lethu ledijithali.',
    'footer.location': 'Harare, Zimbabwe',
    'footer.quick_links': 'Izixhumanisi Ezisheshayo',
    'footer.about_us': 'Ngathi',
    'footer.contact': 'Xhumana Nathi',
    'footer.support': 'Ukusekela',
    'footer.help_center': 'Isikhungo Sosizo',
    'footer.terms_service': 'Imigomo Yesevisi',
    'footer.payment_info': 'Ulwazi Lokukhokha',
    'footer.copyright': '© 2025 ZimbabweApps. Wonke amalungelo agodliwe.',
    'footer.support_email': 'support@zimbabweapps.co.zw',
    
    // Search
    'search.recent_searches': 'Ukudinga Kwakamuva',
    'search.trending': 'Okuthandwayo',
    'search.clear': 'Sula',
    
    // Categories
    'category.finance': 'Ezezimali',
    'category.news': 'Izindaba',
    'category.weather': 'Isimo Sezulu',
    'category.travel': 'Ukuhamba',
    'category.education': 'Imfundo',
    'category.entertainment': 'Ukuzijabulisa',
    'category.business': 'Ibhizinisi',
    'category.health': 'Impilo',
    'category.shopping': 'Ukuthenga',
    'category.social': 'Ezenhlalo',
    'category.productivity': 'Ukukhiqiza',
    'category.games': 'Imidlalo',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return storage.get(STORAGE_KEYS.language, 'en');
  });

  useEffect(() => {
    storage.set(STORAGE_KEYS.language, language);
  }, [language]);

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || translations.en[key] || key;
    
    // Replace parameters in translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }
    
    return translation;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};